version: '2'

services:

    database:
        restart: always
        image: postgres:9.6
        container_name: database
        env_file:
            - ./compose/environ/local.env
        expose:
            - 5432

    webserver:
        image: python:3.6
        container_name: webserver
        build:
            context: .
            dockerfile: ./compose/django/Dockerfile-dev
        links:
            - database
        depends_on:
            - "database"
        env_file:
            - ./compose/environ/local.env
        volumes:
            - .:/app
        ports:
            - 8000:8000
        command: python /app/manage.py runserver 0.0.0.0:8000
